# Generated by Django 4.0.5 on 2022-06-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('NO DEFINIDO', 'no definido'), ('MEME ACTUAL', 'meme actual'), ('MEME CLASICO', 'meme clasico')], default='NO DEFINIDO', max_length=12)),
            ],
        ),
    ]
