# Generated by Django 4.0.5 on 2022-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('SFW', 'sfw'), ('NSFW', 'nsfw')], default='SFW', max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='memes',
        ),
    ]
