# Generated by Django 4.0.5 on 2022-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_board_delete_memes'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='BoardDescription',
            field=models.TextField(default='Pick a description'),
        ),
        migrations.AddField(
            model_name='board',
            name='BoardName',
            field=models.TextField(default='Pick a name'),
        ),
    ]
