# Generated by Django 4.0.5 on 2022-06-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_board_boarddescription_board_boardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='BoardName',
            field=models.CharField(default='Pick a name', max_length=50),
        ),
    ]
