# Generated by Django 4.0.5 on 2022-06-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0004_alter_board_boardname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='BoardDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='BoardName',
            new_name='name',
        ),
    ]
