# Generated by Django 4.0 on 2022-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='newadd',
            field=models.TextField(default='Hola que pasa'),
        ),
    ]
