# Generated by Django 4.0 on 2022-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0007_board_newadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='adminPost',
            field=models.TextField(default='Hola soy el admin'),
        ),
    ]
