# Generated by Django 4.0.5 on 2022-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0009_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(default='images/noimage.jpeg', upload_to='images/'),
        ),
    ]
